# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "66a501c47dd429e1c9f7ef7c13e0ccdc"
name = "qr-generator"
handle = "qr-generator-14"
application_url = "https://cutting-access-commodity-visited.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "appli-testing.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://cutting-access-commodity-visited.trycloudflare.com/auth/callback",
  "https://cutting-access-commodity-visited.trycloudflare.com/auth/shopify/callback",
  "https://cutting-access-commodity-visited.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
